### ISSUE TITLE
Update version of bot

### ISSUE THREAD

**Issue by ArtemDadychenko** [FreebeeTeam/freebee-telegram-bot#6]
Вчера с Егором наткнулись на проблему обновления версии бота.

У него в боте была видна только возможно найти ближайший wifi, хотя у нас были уже и туалеты.

Решилось с помощью ввода `/start` , но не каждый пользователь будет знать что это надо сделать и будет сидеть со старой версией бота.

**Comment by GitStearis** [comment]
@ArtemDadychenko, по сути, новая клавиатура присылается пользователю по команде `/start` и каждый последующий раз после фразы "Что-нибудь еще?". Не думаю, что это может быть заметной проблемой, но я посмотрю, что с этим можно сделать.
